"""item price external ref

Revision ID: 1b573b0c2116
Revises: 42044543028f
Create Date: 2026-09-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b573b0c2116'
down_revision = '42044543028f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ref', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.drop_column('external_ref')

    # ### end Alembic commands ###
