"""ingredient pricing

Revision ID: 1c0199d21e90
Revises: 0b10d67750be
Create Date: 2026-08-31 09:07:59.582907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0199d21e90'
down_revision = '0b10d67750be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_store_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store'))
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_household_id'), ['household_id'], unique=False)

    op.create_table('item_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pack_amount', sa.Float(), nullable=False),
    sa.Column('pack_unit', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_item_price_household_id_household')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_price_item_id_item')),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name=op.f('fk_item_price_store_id_store')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_price')),
    sa.UniqueConstraint('item_id', 'store_id', name='uq_item_price_item_store')
    )
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_price_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_price_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_price_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_feature', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('preferred_store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_household_preferred_store_id_store'), 'store', ['preferred_store_id'], ['id'])

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=16), nullable=True))

    with op.batch_alter_table('shoppinglist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoppinglist_items', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('amount')

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('amount')

    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_household_preferred_store_id_store'), type_='foreignkey')
        batch_op.drop_column('preferred_store_id')
        batch_op.drop_column('pricing_feature')

    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_price_store_id'))
        batch_op.drop_index(batch_op.f('ix_item_price_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_price_household_id'))

    op.drop_table('item_price')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_household_id'))

    op.drop_table('store')
    # ### end Alembic commands ###
