"""item photo

Revision ID: 42044543028f
Revises: a3f7c1d9b2e4
Create Date: 2026-08-31 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42044543028f'
down_revision = 'a3f7c1d9b2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk_item_photo_file'), 'file', ['photo'], ['filename']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_item_photo_file'), type_='foreignkey')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
