"""store photo

Revision ID: 7c2a9e4f1b3d
Revises: 1b573b0c2116
Create Date: 2026-09-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2a9e4f1b3d'
down_revision = '1b573b0c2116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f('fk_store_photo_file'), 'file', ['photo'], ['filename']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_store_photo_file'), type_='foreignkey')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
