"""item price sold loose

Revision ID: ecb27293e7b7
Revises: 1c0199d21e90
Create Date: 2026-08-31 10:08:47.232729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb27293e7b7'
down_revision = '1c0199d21e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_loose', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.drop_column('sold_loose')

    # ### end Alembic commands ###
